### ISSUE TITLE
The name of PCT

### ISSUE THREAD

**Issue by MenghaoGuo** [lulutang0608/Point-BERT#1]
Congratulations on publishing such a great paper. 

I am the author of PCT: Point Cloud Transformer. Thanks for citing our work. However, i note that you use a wrong name for our PCT which you call it PTC in Table 1.   Could you correct it?

Best,

Menghao

**Comment by yuxumin** [comment]
@MenghaoGuo So sorry that we wrongly spell the name for your method. We will correct it.

Best, 
Xumin
