### ISSUE TITLE
Pre-training Point-BERT and dVAE on other datasets

### ISSUE THREAD

**Issue by eliahuhorwitz** [lulutang0608/Point-BERT#10]
Hey,
In the runner and runner_BERT_pretrain scripts there is a check for dataset name and if it's not ShapeNet (or ModelNet for runner_BERT_pretrain), a NotImplementedError is thrown.
What do I need to change/add/remove in order to run the pertaining and dVAE on other datasets (ScanObjectNN or ScanNet for example)?

Thanks,
Eliahu

**Comment by yuxumin** [comment]
Hi,
Thanks for your interest in our work.

1) Create your dataset class under `datasets` directory. And remember to put the class into registry. 
2)  Initialize the custom dataset class by importing it in `datasets/__init__.py`
3)  Change the dataset config in certrain method config.
4)  Modify the code in `tools/runner.py`. ( check the dataset name and preprocess the data for model)

Then you can run the code on your own dataset.

reference: [issue 11](https://github.com/yuxumin/PoinTr/issues/11)

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
