### ISSUE TITLE
Question about the position embedings

### ISSUE THREAD

**Issue by Zhimin-C** [lulutang0608/Point-BERT#11]
Thanks for the great job!  I have a question about the usage of position embeddings in the transformer encoder.
![Screenshot from 2021-12-25 22-42-58](https://user-images.githubusercontent.com/35618385/147398351-92143b04-904b-4ab8-8fba-bad870f9f804.png)
As shown in the picture, the position embeddings are given for each layer. I am curious about why not only add the position embeddings in the first layer? Thanks.

Zhimin Chen

**Comment by yuxumin** [comment]
Hi, Zhimin. 

Thanks for your interest in our work.
We find that adding the position embedding to each layer in encoder can help point transformer converenge more stably.

Best!
