### ISSUE TITLE
failed to build pointnet2_ops_lib 

### ISSUE THREAD

**Issue by leeyegy** [lulutang0608/Point-BERT#12]
when run the command to build pointnet2_ops_lib, some errors occur:
......

  1.10.0.git.kitware.jobserver-1
    g++ -pthread -shared -B /mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/compiler_compat -L/mnt/cache/share/spring/conda_envs/miniconda3/envs/s0.3.4/lib -Wl,-rpath=/mnt/cache/share/spring/conda_env
s/miniconda3/envs/s0.3.4/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/group_points.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86
_64-3.6/pointnet2_ops/_ext-src/src/bindings.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/ball_query.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_op
s/_ext-src/src/sampling.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/interpolate.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/samp
ling_gpu.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/group_points_gpu.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/ball_query_gpu
.o /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/interpolate_gpu.o -L/mnt/cache/liyanjie/.local/lib/python3.6/site-packages/torch/lib -L/mnt/cache/share/cuda-10.2/lib64 -lc1
0 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.6/pointnet2_ops/_ext.cpython-36m-x86_64-linux-gnu.so
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/group_points.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/bindings.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/ball_query.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/sampling.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/interpolate.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/sampling_gpu.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/group_points_gpu.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/ball_query_gpu.o: No such file or directory
    g++: error: /tmp/pip-req-build-cn253nrh/build/temp.linux-x86_64-3.6/pointnet2_ops/_ext-src/src/interpolate_gpu.o: No such file or directory

**Comment by leeyegy** [comment]
My GCC version is 5.4.0; pytorch 1.7.1
I have no idea why these errors happen.
And any suggestions would be appreciated.

**Comment by yuxumin** [comment]
Hi, can you provide the complete log while building the pointnet2_lib?

**Comment by leeyegy** [comment]
Thanks for your reply very much. 
I found the solution:
For V100, the errors above occur when using CUDA-9.0 or CUDA-10.2. Everything is gonna be just fine when set the CUDA exactly as 10.0

**Comment by SimingYan** [comment]
Hi @leeyegy, I got the same issue on V100. May I ask how you install torch >= 1.7.0 when setting CUDA=10.0? Thanks!
