### ISSUE TITLE
`validation` v.s. `vote validation`

### ISSUE THREAD

**Issue by ShoufaChen** [lulutang0608/Point-BERT#15]
Hi,

Hello, would you please explain what's the difference between **validation acc** and **vote validation acc**?
And, which one is used in the paper's tables?

**Comment by yuxumin** [comment]
Hi,

`vote validation acc` is the accuracy using voting strategy during the test, while `validation acc` is not.  
`Voting`:  We add different augmentations to the input, and inference them using our model. Then the final prediction is made by them. 
`vote validation acc` is used in the table for ModelNet40.

**Comment by ShoufaChen** [comment]
Thanks for your reply.

**Comment by junshengzhou** [comment]
Hi. Thank you for your great work. 

Did other works(eg. PointTransformer) use the same **voting** strategy? It seems like the results reported on the paper is vote validation acc.
