### ISSUE TITLE
Part segmentation details

### ISSUE THREAD

**Issue by Pang-Yatian** [lulutang0608/Point-BERT#17]
Hi,

Thanks for your great work.

May I ask when do you plan to release part segmentation codes?

We are trying to reproduce the part segmentation results and meet some issues due to lack of details in paper and appendix. Regarding segmentation head, could you please provide more details about how the upsampled feature H4<sup>^</sup>, H8<sup>^</sup> with H12 being propagated by 1 MLP and 8 DGCNN blocks?

Looking forward to your kind reply.

Best regards,
Yatian

**Comment by yuxumin** [comment]
Hi Yatian,
 
Sorry for the delay of releasing codes. We plan to release the codes for PartSeg around April. As the codes for PartSeg is based on [PointNet2 codebase](https://github.com/yanx27/Pointnet_Pointnet2_pytorch), it requires some effects to merge the two tasks into the current codebase.

For each propagation step, we use a two layer DGCNN. In each layer, we do:
1) build a local graph via kNN. In this step, we can find a local region (containing `k` points) in the sparser cloud for each single point in the denser cloud.
2) update the feature `f` for this single point in denser cloud followed by DGCNN : ( `g` represents the features from local region of sparser cloud) .  Expand the last dimension of `f` to `k`. Then concat `f` and `g-f`. and send it into an MLP. Finally max pool the concatenated feature on `k` dimension.

Feel free to update this issue if any more questions.

Best!

**Comment by Pang-Yatian** [comment]
> Hi Yatian,
> 
> Sorry for the delay of releasing codes. We plan to release the codes for PartSeg around April. As the codes for PartSeg is based on [PointNet2 codebase](https://github.com/yanx27/Pointnet_Pointnet2_pytorch), it requires some effects to merge the two tasks into the current codebase.
> 
> For each propagation step, we use a two layer DGCNN. In each layer, we do:
> 
> 1. build a local graph via kNN. In this step, we can find a local region (containing `k` points) in the sparser cloud for each single point in the denser cloud.
> 2. update the feature `f` for this single point in denser cloud followed by DGCNN : ( `g` represents the features from local region of sparser cloud) .  Expand the last dimension of `f` to `k`. Then concat `f` and `g-f`. and send it into an MLP. Finally max pool the concatenated feature on `k` dimension.
> 
> Feel free to update this issue if any more questions.
> 
> Best!

Thanks for your answer. However I am still a little bit confused.
1. Are the local knn and DGCNN the same as implementation in dVAE?
[https://github.com/lulutang0608/Point-BERT/blob/97fe9e26bf515b27dd7c0fc541f21bc40cfa9b5b/models/dvae.py#L53](url)

2. How come there are 4 propagation steps, as there are only 3 different levels of feature(H4^, H8^, H12)?  And where is the 4-layer MLP being implemented? Is there any additional concatenate opreation between (H4^, H8^, H12) and the updated feature `f`?

I would appreciate it if you feel comfortable to provide the part of seg head model code. Thank you very much.

**Comment by yuxumin** [comment]
1) Yes, we adopt a light-weight version of two layer. (dVAE adopts four-layer design)
2) Sorry for misleading, there only exists *three* propagation steps. We will correct the paper after the codes release. 
3) Is 4-layer MLP the first term in Table. 6. Segmentation Head? This is a 2-layer MLP with 4x middle channel, using for `Geometry-based feature upsampling` (as the same as PointNetFeaturePropagation)
4) Concatenation operation only exists in DGCNN layer.

> I would appreciate it if you feel comfortable to provide the part of seg head model code. Thank you very much.

Yes, that's all right. I will email you the code of PartSeg head. Could you give me your email address. After checking the head code, i find some misleading descriptions may cause lots of problems for re-implementing this part.

**Comment by Pang-Yatian** [comment]
> 1. Yes, we adopt a light-weight version of two layer. (dVAE adopts four-layer design)
> 2. Sorry for misleading, there only exists _three_ propagation steps. We will correct the paper after the codes release.
> 3. Is 4-layer MLP the first term in Table. 6. Segmentation Head? This is a 2-layer MLP with 4x middle channel, using for `Geometry-based feature upsampling` (as the same as PointNetFeaturePropagation)
> 4. Concatenation operation only exists in DGCNN layer.
> 
> > I would appreciate it if you feel comfortable to provide the part of seg head model code. Thank you very much.
> 
> Yes, that's all right. I will email you the code of PartSeg head. Could you give me your email address. After checking the head code, i find some misleading descriptions may cause lots of problems for re-implementing this part.

Thank you so much for detailed explanation! My email is pang_yatian@163.com. It is so kind of you.

**Comment by ANABUR920** [comment]
Hi, xumin. Very solid work, would you mind sharing with me a copy of the Part-Seg wise code. My add is swe1709118@xmu.edu.my

**Comment by liang3588** [comment]
Very solid work, would you mind also sharing with me a copy of the Part-Seg wise code. My email is yqliang@whu.edu.cn. Thank you!
