### ISSUE TITLE
multiply loss by 1000 for log

### ISSUE THREAD

**Issue by ShoufaChen** [lulutang0608/Point-BERT#19]
Hi,

I was wondering are there any specific reasons that multiply loss by 1000 for log here?

https://github.com/lulutang0608/Point-BERT/blob/97fe9e26bf515b27dd7c0fc541f21bc40cfa9b5b/tools/runner.py#L147-L149

**Comment by yuxumin** [comment]
Hi, no any specific reasons. Because the loss_CD is too small (always < 1e-3 ), just for a better observation for loss.

**Comment by ShoufaChen** [comment]
Thanks for your reply.
