### ISSUE TITLE
I want to know what the 'name' mean?

### ISSUE THREAD

**Issue by liang3588** [lulutang0608/Point-BERT#2]
![image](https://user-images.githubusercontent.com/82434236/144580636-f7ec7cd5-5ef3-4f44-b396-b560e8f8c731.png)
I want to know what the 'name' means in the third line '--exp_name <name>'.
Thank you very much!

**Comment by yuxumin** [comment]
Hi @liang3588 . Sorry for confusion. `name`  is a string, representing the name of your experiment this time.
For example. `--exp_name test_dvae`

**Comment by liang3588** [comment]
Thank you for explaining!
