### ISSUE TITLE
Linear SVM result drops

### ISSUE THREAD

**Issue by EternityDS** [lulutang0608/Point-BERT#20]
Hi,

Thanks for your great work! I have one quick question here.

I am trying to pre-train point-bert by myself. And I notice the Linear SVM evaluation result drops with the pre-training going. May I ask is this normal? I attached my training visual log here.

![image](https://user-images.githubusercontent.com/20315468/152666526-2bb248ee-2952-48f2-a8d4-0b7c8efe95f7.png)

**Comment by yuxumin** [comment]
Hi,

Yes, i think it is normal for the LinearSVM performance drop.

The MPM pre-training encourages the Transformer to reconstruct local patches, which pays more attention to low-level geometry rather than high-level semantics.

**Comment by EternityDS** [comment]
Thanks! Got it.
