### ISSUE TITLE
A question regarding the voting code

### ISSUE THREAD

**Issue by Pang-Yatian** [lulutang0608/Point-BERT#21]
Hi,
 
Thank you for releasing the code.

I refer to [RS-CNN voting code](https://github.com/Yochengliu/Relation-Shape-CNN/blob/master/voting_evaluate_cls.py#L68) and have a question regarding [your voting code](https://github.com/lulutang0608/Point-BERT/blob/master/tools/runner_BERT_finetune.py#L382)

```
  for time in range(1, 10):
            this_acc = test_vote(base_model, test_dataloader, 1, None, args, config, logger=logger, times=time)
            if acc < this_acc:
                acc = this_acc
```
From my understanding, `for time in range(1, 10):` means repeat voting. Hence, `time` should not be passed in to `test_vote(base_model, test_dataloader, 1, None, args, config, logger=logger, times=time)`. Am I correct or did I miss some points?

Looking forward to your reply. Best regards!

**Comment by yuxumin** [comment]
Hi, thanks for your interest in our work and sorry for the late reply. 
It is a typo, we will correct it.
Thanks a lot for pointing it out.

**Comment by Pang-Yatian** [comment]
Thanks for your reply. Congrats to you that your paper has been accepted to CVPR.
