### ISSUE TITLE
pip can't install open3d==0.9 due to version

### ISSUE THREAD

**Issue by zhiweidaxia** [lulutang0608/Point-BERT#22]
Collecting h5py
  Downloading h5py-3.6.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 67.1 MB/s
Collecting matplotlib
  Downloading matplotlib-3.5.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 34.4 MB/s
Collecting numpy
  Downloading numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     |████████████████████████████████| 16.8 MB 131.3 MB/s
ERROR: Could not find a version that satisfies the requirement open3d==0.9 (from versions: 0.10.0.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.13.0, 0.14.1)
![1644596906(1)](https://user-images.githubusercontent.com/47274725/153630675-5c517604-5f23-46b3-abfb-ca3a1c09ca48.png)

ERROR: No matching distribution found for open3d==0.9

I used conda create a virtual environment which based on python3.8, but it can not install open3d==0.9.
Then I changed the version of python(python3.7) in virtual environment, which is Successful
![image](https://user-images.githubusercontent.com/47274725/153630792-f5288248-f9fe-406a-8b59-559e9445478e.png)

**Comment by yuxumin** [comment]
Hi, sorry for the late reply.
Yes, it seems that o3d 0.9 requires python verison 3.7.
I will correct the requirement description in our repo. Thanks a lot!

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
