### ISSUE TITLE
About "vocabulary" in paper

### ISSUE THREAD

**Issue by WrongMalik** [lulutang0608/Point-BERT#24]
Hello, thanks for your great work.
I have some questions about the "vocabulary" mentioned in the paper. How is it acquired? Is it learned during the dVAE-based point cloud reconstruction?
Hoping for the answer, thanks.

**Comment by yuxumin** [comment]
Yes, it is learned during dVAE reconstruction.

**Comment by WrongMalik** [comment]
> Yes, it is learned during dVAE reconstruction.

thanks a lot
