### ISSUE TITLE
log issue

### ISSUE THREAD

**Issue by antoalli** [lulutang0608/Point-BERT#25]
Hi! 
Thanks for the interesting work and for publishing the code.
I've encountered a little bug/typo when training the DVAE with DistributedDataParallel, it affects only the loss logging:
https://github.com/lulutang0608/Point-BERT/blob/c1df1e85a53c4fecbba518e3adc3cd3f165aaab1/tools/runner.py#L146
Should be: loss_2 = dist_utils.reduce_tensor(loss_2, args)
Antonio

**Comment by yuxumin** [comment]
Hi,

Thanks for pointing it out. Sorry for the typo. We will correct it.  :)
