### ISSUE TITLE
error when bash install 

### ISSUE THREAD

**Issue by ruoshui252844** [lulutang0608/Point-BERT#27]
Hi Dear all, 
I meet a problem when python setup.py install --user
it turns out:

> running install
> /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/anaconda3$/envs/MaskTop/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   setuptools.SetuptoolsDeprecationWarning,
> /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/anaconda3$/envs/MaskTop/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>   EasyInstallDeprecationWarning,
> running bdist_egg
> running egg_info
> creating emd_ext.egg-info
> writing emd_ext.egg-info/PKG-INFO
> writing dependency_links to emd_ext.egg-info/dependency_links.txt
> writing top-level names to emd_ext.egg-info/top_level.txt
> writing manifest file 'emd_ext.egg-info/SOURCES.txt'
> reading manifest file 'emd_ext.egg-info/SOURCES.txt'
> writing manifest file 'emd_ext.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_ext
> building 'emd_cuda' extension
> creating /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build
> creating /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build/temp.linux-x86_64-3.7
> creating /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build/temp.linux-x86_64-3.7/cuda
> Emitting ninja build file /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build/temp.linux-x86_64-3.7/build.ninja...
> Compiling objects...
> Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
> 1.10.2
> creating build/lib.linux-x86_64-3.7
> g++ -pthread -B /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/anaconda3$/envs/MaskTop/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/anaconda3$/envs/MaskTop/compiler_compat -L/media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/anaconda3$/envs/MaskTop/lib -Wl,-rpath=/media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/anaconda3$/envs/MaskTop/lib -Wl,--no-as-needed -Wl,--sysroot=/ /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build/temp.linux-x86_64-3.7/cuda/emd.o /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build/temp.linux-x86_64-3.7/cuda/emd_kernel.o -L/media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/anaconda3$/envs/MaskTop/lib/python3.7/site-packages/torch/lib -L/usr/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/emd_cuda.cpython-37m-x86_64-linux-gnu.so
> g++: error: /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build/temp.linux-x86_64-3.7/cuda/emd.o: No such file or directory
> g++: error: /media/ly/1dc08886-9b59-45c8-809c-468f28b98ce1/Point-BERT/extensions/emd/build/temp.linux-x86_64-3.7/cuda/emd_kernel.o: No such file or directory
> error: command '/usr/bin/g++' failed with exit code 1

I want to know if it works for my satuation:
NVCC V10.1.243
gcc 9.4.0
pytorch 1.7.1 with cuda 10.1

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist

**Comment by kaali-billi** [comment]
I ran into a similar issue '  fatal error C1070: mismatched #if/#endif pair in file 'C:\Users\s365026\Desktop\*******\Point-BERT\extensions\emd\cuda\emd_kernel.cu ' '
