### ISSUE TITLE
How to install chamfer?

### ISSUE THREAD

**Issue by liang3588** [lulutang0608/Point-BERT#3]
"ModuleNotFoundError: No module named 'chamfer'. " I want to install chamfer by pip install chamfer, but it reminds 
![image](https://user-images.githubusercontent.com/82434236/144810173-9b00b45c-dc58-4787-b3e4-77405bb9717d.png)
So, how should I install the 'chamfer' module?
Thank you very much!

**Comment by yuxumin** [comment]
Hi, @liang3588.  Chamfer can not be installed by pip. Go to `extensions/chamfer_dist` and run `python setup.py install --user`. (reference: [here](https://github.com/yuxumin/PoinTr/issues/6). )

**Comment by liang3588** [comment]
Thank you! It is very kind of you!

**Comment by RavenScroft863** [comment]
> 

but where is the 'extensions' file
