### ISSUE TITLE
What does _random_replace do?

### ISSUE THREAD

**Issue by Hiusam** [lulutang0608/Point-BERT#30]
Hi, thank you for your great work.
I just find it difficult to understand what _random_replace() in MaskTransformer does. Can you give me some hints? Thank you!

**Comment by yuxumin** [comment]
Hi,  thanks for you interest in our work.
 _random_replace() is an augmentation. We study random_mask and random_replace in Table. 5

**Comment by yuxumin** [comment]
Close it since no response. Feel free to re-open it if problems still exist
