### ISSUE TITLE
What is the difference between point cloud completion task and point cloud masked reconstruction?

### ISSUE THREAD

**Issue by jlqzzz** [lulutang0608/Point-BERT#35]
First of all, thank you for your outstanding work!

The pretext task used in your pre-training phase is point cloud masked reconstruction. 

I wonder what's the difference between point cloud completion task and point cloud masked reconstruction? For example, Point-BERT (pre-training phase) vs PoinTr. Although the implementation details may be different, what are the essential differences in tasks?

**Comment by yuxumin** [comment]
Hi, thanks for your interest in our work.
The most essential difference is that in point cloud completion, the position encoding of the missing patch is unknown, while in PointBERT, the coarse position information of the point patch is given.

**Comment by jlqzzz** [comment]
> Hi, thanks for your interest in our work. The most essential difference is that in point cloud completion, the position encoding of the missing patch is unknown, while in PointBERT, the coarse position information of the point patch is given.

I get it! Thank you!
