### ISSUE TITLE
Training questions about dVAE

### ISSUE THREAD

**Issue by sw778** [lulutang0608/Point-BERT#47]
What do the three Metrics in "Metrics" mean when training dVAE? How to judge whether the trained dVAE is good or bad according to these three indicators?
![IMG_20220607_125919](https://user-images.githubusercontent.com/81848293/172300079-7f116767-3d11-4bdf-bb79-4a1cf3919dc1.jpg)

**Comment by yuxumin** [comment]
Hi, these three metrics are F1-Score (higher is better),  CD-L1 * 1000 (lower is better), CD-L2 * 1000 (lower is better).

**Comment by sw778** [comment]
Thank you for your reply！
