### ISSUE TITLE
How can I get the preprocessed data for fine-tuning?

### ISSUE THREAD

**Issue by zhaozj89** [lulutang0608/Point-BERT#52]
Thanks for sharing this work.

In [DATASET.md](https://github.com/lulutang0608/Point-BERT/blob/master/DATASET.md), the processed ModelNet dataset is provided. I would like to inquire how to process the official ModelNet to get that data format so that I can fine-tune the model with other datasets. Thanks very much.

**Comment by yuxumin** [comment]
Hi @zhaozj89, we follow https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/data_utils/ModelNetDataLoader.py to process ModelNet40. Official ModelNet provides point cloud form of models, so simple fps is done to obtain the final used data. If you want to generate point cloud from mesh data, plz refer to https://github.com/yuxumin/PoinTr/blob/master/datasets/shapenet2pc.py

Best regards

**Comment by zhaozj89** [comment]
Thanks!
