### ISSUE TITLE
About the ShapeNet55/34 Dataset

### ISSUE THREAD

**Issue by Gary-Deeplearning** [lulutang0608/Point-BERT#7]
Hi, hank you for the great work!

I downloaded the ShapeNet55/34 Dataset from the link of BaiduCloud, but I did not find these data(ShapeNet-35 train.txt test.txt) when I unzipped it. Is there any problem?

**Comment by yuxumin** [comment]
Hi,  I put the `test.txt` and `train.txt` in `data/ShapeNet55-34/ShapeNet-55/` folder.  Find it [here](https://github.com/lulutang0608/Point-BERT/blob/master/data/ShapeNet55-34/ShapeNet-55/test.txt)

**Comment by Gary-Deeplearning** [comment]
Oh, got it.
Thanks.
