### ISSUE TITLE
Pre-training and Fine-tuning times

### ISSUE THREAD

**Issue by eliahuhorwitz** [lulutang0608/Point-BERT#9]
Hey,
Thanks for publishing the code, these are indeed very impressive results! 
Could you please elaborate on how long it took for the pre-training and fine-tuning and on what type of hardware?

Thanks!

**Comment by yuxumin** [comment]
Hi, thanks for your interest in our work.
For pre-training, it takes about 22 hours on two Nvidia 2080Ti or 28 hours on one Nvidia 3090.
For Fine-tuning, it takes about 9 hours on one Nvidia 2080 Ti and 5 hours on one Nvidia 3090.

**Comment by eliahuhorwitz** [comment]
Thanks for the quick response! 
Are these times including the dVAE training or is it just for the MPM part?

**Comment by yuxumin** [comment]
The 22 hours for pre-training is only conclude MPM part. The training of dVAE takes another 20 hours on one Nvidia 2080Ti at the beginning.

**Comment by eliahuhorwitz** [comment]
Thanks!
